package com.loveseriously.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.loveseriously.service.IMyService;

import javax.swing.*;
import java.awt.*;

/**
 * @author lw
 * @date 2019-08-22
 */
public class MySettingUI {
    public JPanel rootPanel;
    public JLabel tile;
    public JEditorPane editorPane;

    private void createUIComponents() {
        this.editorPane = new JEditorPane();
    }

    public void setData(IMyService data) {
        editorPane.setText(data.getEitContent());
    }

    public void getData(IMyService data) {
        data.setEitContent(editorPane.getText());
    }

    public boolean isModified(IMyService data) {
        return editorPane.getText() != null ? !editorPane.getText().equals(data.getEitContent()) : data.getEitContent() != null;
    }

    public JComponent getRootComponent() {
        return this.rootPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        tile = new JLabel();
        tile.setText("测试编写保存文字");
        rootPanel.add(tile, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        rootPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        editorPane.setBackground(new Color(-855310));
        editorPane.setText("请输入内容");
        editorPane.setToolTipText("请在此编辑文字");
        rootPanel.add(editorPane, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
