import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * @author lw
 * @date 2019-08-22
 */
public class HelloWorldConfiguration {
    private JPanel rootComponent;
    private JLabel phraseLabel;
    private JTextField phraseField;

    private void createUIComponents() {
        this.rootComponent = new JPanel();
        this.phraseLabel = new JLabel();
    }

    public HelloWorldConfiguration() {
        $$$setupUI$$$();
        phraseLabel.setLabelFor(phraseField);
    }


    public void setData(HelloWorldApplicationComponent data) {
        phraseField.setText(data.getPhrase());
    }

    public void getData(HelloWorldApplicationComponent data) {
        data.setPhrase(phraseField.getText());
    }

    public boolean isModified(HelloWorldApplicationComponent data) {
        return phraseField.getText() != null ? !phraseField.getText().equals(data.getPhrase()) : data.getPhrase() != null;
    }

    public JComponent getRootComponent() {
        return this.rootComponent;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootComponent.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        phraseLabel.setText("Label");
        rootComponent.add(phraseLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        phraseField = new JTextField();
        phraseField.setText("");
        rootComponent.add(phraseField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootComponent;
    }
}
